POST http://localhost:5050/newOrder/650c38d1045af49fb36aefb9
Content-Type: application/json

{
    "userId": "650c38d1045af49fb36aefb9",
    "cart": {
        "product": "Candela profumata alla cannella e vaniglia",
        "price": 20.8
    },
    "state": "processing",
    "shippingAddress": {
        "address": "via dell",
        "zip": 51010
    }
}

####
GET http://localhost:5050/orders