GET http://localhost:5050/users

####
POST http://localhost:5050/user/registration
Content-Type: application/json

{
    "name": "Francesca",
    "surname": "D'Anna",
    "email": "francescadanna@gmail.com",
    "password": "francescadanna",
    "shippingAddress":{
        "address": "via della cavaccia 9b",
        "city": "Uzzano",
        "state": "Pistoia",
        "zipCode": 51010,
        "country": "Italia"
    },
    "phone": {
        "prefix": 39,
        "number": 3331313371
    },
    "role": "user"
}

####

GET http://localhost:5050/user/cart/64f88cce8055d5a8d36b9590